[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800  # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.26"
src = "src"
test = "test"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
via_ir = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
base = { key = "${API_KEY_BASESCAN}" }
base_sepolia = { key = "${API_KEY_BASESCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
